#!/bin/bash

USER=rhel

# Set the target directory and file
target_directory="/home/rhel/ansible-files"
target_file="${target_directory}/system_setup.yml"
solve_file="/tmp/first-101/solve_11_system_setup.yml"


# Set the target directory and 
cd $target_directory
su - $USER -c 'cd ~/ansible-files && ansible-navigator inventory --list -m stdout'
chown -R rhel:rhel $target_directory