#!/bin/bash

USER=rhel

# Set the working directory
# Define the desired hosts file content
# Write the desired content to the 'hosts' file
su - $USER -c 'cat >/home/rhel/ansible-files/hosts <<EOL
[web]
node1
node2

EOL
cat /home/rhel/ansible-files/hosts'
