---
- name: Basic System Setup
  hosts: web
  become: true
  tasks:
    - name: Update all security-related packages
      ansible.builtin.dnf:
        name: 'kernel'
        state: latest
        security: true

    - name: Create a new user
      ansible.builtin.user:
        name: myuser
        state: present
        create_home: true
